name: flutter_cupertino_localizations_nomad483
description: flutter_cupertino_localizations_nomad483
version: 1.0.2
author: nomad483
homepage: https://github.com/nomad483/flutter_cupertino_localizations

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.7"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
